version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    network_mode: host

  redis-exporter:
    image: oliver006/redis_exporter
    container_name: redis-exporter
    ports:
      - "9121:9121"
    environment:
      REDIS_ADDR: "localhost:6379"
    depends_on:
      - redis
    network_mode: host

  solid-connection-stage:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solid-connection-stage
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=stage
    depends_on:
      - redis
    network_mode: host
